//! Default name of this device — the one others see in the sync list
//! before the user changes it by hand.
//!
//! It has to be recognizable at a glance: with two PCs and a phone,
//! "Android" and "Sway" don't distinguish anything.
//!
//! On Android the name only exists on the Java side (`Settings.Global` /
//! `android.os.Build`), so `MainActivity` resolves it and leaves it in the
//! `SWAY_DEVICE_NAME` environment variable before the Rust runtime starts.
//! Reading it via JNI from here was tried and **doesn't work**:
//! `ndk_context::android_context()` does `.expect(...)` and Tauri never
//! initializes that context, so the panic aborts the process at startup.

/// Names generated by an earlier version that don't identify the device.
/// If the stored name is one of these it gets recalculated, instead of
/// leaving the phone called "Android" forever.
pub const PLACEHOLDERS: &[&str] = &["Android", "Sway", "localhost"];

/// Variable populated by `MainActivity` on Android. On desktop it doesn't
/// exist and it falls back to the machine name.
const ENV_DEVICE_NAME: &str = "SWAY_DEVICE_NAME";

pub fn default_device_name() -> String {
    [ENV_DEVICE_NAME, "COMPUTERNAME", "HOSTNAME"]
        .iter()
        .find_map(|k| std::env::var(k).ok())
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty() && !PLACEHOLDERS.contains(&s.as_str()))
        .unwrap_or_else(|| {
            if cfg!(target_os = "android") { "Android".into() } else { "Sway".into() }
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_name_is_never_empty_and_never_a_placeholder_on_desktop() {
        let name = default_device_name();
        assert!(!name.is_empty());
        if !cfg!(target_os = "android") {
            assert_ne!(name, "Android");
        }
    }
}
